Reimplement Japanese segmenter
meilisearch/charabia pull request #105
Opened 2022-05-24 13:59 UTC by loiclec

# Pull Request

## What does this PR do?
Fixes #89 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

## Notes

* This PR adds a `japanese` feature flag which depends on `lindera` and `lindera-core`. These are the crates performing the actual segmenting. The two Japanese dictionary features of `lindera` are used. I have not checked whether both are strictly necessary.
* I have added only one unit test. The benchmarks seemed to already include Japanese text, so I assumed that there was no need to add another one.
* The existing Chinese normaliser was previously triggered on `script ==  Cj`, which meant it was also triggered on Japanese text. I have made it stricter to avoid normalising Japanese text. Now it only triggers when the language is known as `Cmn`.
* `lindera`'s `tokenize_str` method returns a `Result`. It is not clear to me on what conditions this method fails. A previous implementation of the Japanese segmenter on this repo `unwrap`ed the result.  I have done the same thing, but have low confidence on the correctness of that approach.
* Japanese compounded words are decomposed by using the following configuration:
```rust
TokenizerConfig { mode: Mode::Decompose(Penalty::default()), ..TokenizerConfig::default() }
```
* I have tried to avoid initialising `Lindera`every time by storing it in a static `Lazy`, as recommended in the dummy example.

2022-05-24 14:40 UTC, ManyTheFish requested changes

2022-05-24 14:40 UTC, ManyTheFish commented on src/segmenter/japanese.rs
> +        Box::new(segment_iterator)
```suggestion
        let segments = LINDERA.tokenize_str(to_segment).unwrap();
        Box::new(segments.into_iter())
```
This should work and I find it easier to read, what do you think? 😄 

About the unwrap I'll investigate later 🤔

2022-05-25 07:28 UTC, ManyTheFish commented
Good job @loiclec! Thank you for your contribution!
bors merge

2022-05-25 08:06 UTC, curquiza commented
@ManyTheFish you need to approve to be able to merge 😇

2022-05-25 08:59 UTC, ManyTheFish approved these changes
Thank you @curquiza!
bors merge

2022-05-25 09:12 UTC, merged