Fix typo in docstring
meilisearch/charabia pull request #106
Opened 2022-06-02 20:38 UTC by matthias-wright

This is just a tiny change but while reading the code I noticed that in the docstring of the [`original_lengths`](https://github.com/meilisearch/charabia/blob/1dcaf3cd872d36ad66be41368ab2a97892980a90/src/token.rs#L128) method, the example still uses the old name `num_chars_from_bytes`.

2022-06-07 13:06 UTC, ManyTheFish requested changes

2022-06-07 13:06 UTC, ManyTheFish commented on src/token.rs
> +    /// `original_lengths(11)` for this token will return `(3, 6)` - the number of `(characters, bytes)` in
```suggestion
    /// For example, consider the string "léopard" which gets normalized to "leopard".
    /// `original_lengths(4)` for this token will return `(3, 4)` - the number of `(characters, bytes)` in
```

2022-06-07 13:08 UTC, ManyTheFish commented
Hello @matthias-wright, Thank you for your PR, I completely forgot to update this documentation.
I requested some changes taking into account your comment in issue #99.

2022-06-07 18:36 UTC, matthias-wright commented
Hi @ManyTheFish, thanks for the review! I included your changes in the new commit.

2022-06-08 08:43 UTC, matthias-wright commented on src/token.rs
> +    /// `original_lengths(3)` for this token will return `(3, 4)` - the number of `(characters, bytes)` in
sure, thanks for noticing :D

2022-06-08 08:45 UTC, ManyTheFish approved these changes
Hey @matthias-wright, Thanks for your PR! 🎉
bors merge

2022-06-08 08:51 UTC, merged