Add Thai segmenter
meilisearch/charabia pull request #114
Opened 2022-08-11 08:21 UTC by aFluffyHotdog

# Pull Request
- Implement `ThaiSegmenter`
- add tests
- add benchmarks

## What does this PR do?
Fixes [#113](https://github.com/meilisearch/charabia/issues/113)

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-08-11 11:49 UTC, ManyTheFish commented
Hello @aFluffyHotdog! 
Your work seems promising, do you have any issue finishing it?

2022-08-11 12:54 UTC, aFluffyHotdog commented
@ManyTheFish Oh I just forgot to package the dictionary required for the tokenizer to work, I'll reopen the pull request.

2022-08-11 16:06 UTC, ManyTheFish commented
No problem! Ping me when the PR is ready or if you have any question 😄

2022-08-11 16:20 UTC, ManyTheFish commented on benches/bench.rs
> +    ((132, Script::Thai, Language::Tha), "เราจะทำตามสัญญาขอเวลาอีกไม่นานแล้วแผ่นดินที่งดงามจะคืนกลับมาเราจะทำอย่างซื่อตรงขอแค่เธอจงไว้ใจและศรัทธาแผ่นดินจะดีในไม่ช้า"),
```suggestion
    ((366, Script::Thai, Language::Tha), "เราจะทำตามสัญญาขอเวลาอีกไม่นานแล้วแผ่นดินที่งดงามจะคืนกลับมาเราจะทำอย่างซื่อตรงขอแค่เธอจงไว้ใจและศรัทธาแผ่นดินจะดีในไม่ช้า"),
```

2022-08-12 02:51 UTC, aFluffyHotdog commented
> No problem! Ping me when the PR is ready or if you have any questions 😄
> 
> I would like to know the source of your dictionary, can you add an URL somewhere in the implementation?
> 
> In another hand, I would like to warn you about the content of the dictionary, it contains really long terms like `กรมสมเด็จพระเทพรัตนราชสุดาฯ สยามบรมราชกุมารี` and the library that you use will segment the text matching the longest term found. Is it expected for `กรมสมเด็จพระเทพรัตนราชสุดาฯ สยามบรมราชกุมารี` to be considered as a unique word?

So the dictionary came from PyThaiNLP (a thai NLP library for python). Regarding that word, it is considered to be unique, it is the name of the queen which might explain why it was added into the dictionary.

2022-08-14 08:51 UTC, aFluffyHotdog commented
Ready for review! :D @ManyTheFish

2022-08-16 08:59 UTC, ManyTheFish commented
Hello @aFluffyHotdog, thank you for your PR!

Could you make some changes before we merge it to the main branch:
- Make a cargo fmt pass, in order to format the code
- Move the dictionary in a directory at the root of the repository
- Fix the tests running `cargo test`

Thank you again!

2022-08-16 10:24 UTC, aFluffyHotdog commented
Got it!

2022-08-17 06:38 UTC, aFluffyHotdog commented
@ManyTheFish  All good to go!

<img width="635" alt="image" src="https://user-images.githubusercontent.com/93137058/185051485-38f4d9f7-6edd-40ae-a157-857c74da5e8b.png">

2022-08-17 08:40 UTC, ManyTheFish requested changes

2022-08-17 08:40 UTC, ManyTheFish commented on src/segmenter/thai.rs
> +use std::{ffi::OsStr, fs, path::Path};
```suggestion
```

2022-08-17 13:15 UTC, ManyTheFish commented
Thank you @aFluffyHotdog!
Bors merge

2022-08-17 13:22 UTC, ManyTheFish approved these changes

2022-08-17 13:23 UTC, ManyTheFish commented
bors merge

2022-08-17 13:28 UTC, merged