Disable HMM feature of Jieba
meilisearch/charabia pull request #140
Opened 2022-10-02 13:17 UTC by aniketh-varma

# Pull Request

## What does this PR do?
Fixes #136 

## PR checklist
Please check if your PR fulfills the following requirements:
- [x] Does this PR fix an existing issue?
- [x] Have you read the contributing guidelines?
- [x] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-10-03 08:46 UTC, ManyTheFish requested changes
Hello @aniketh-varma!
Thanks for your pull request, I requested a small change in it.
I will merge the PR after you made the change. 😄

2022-10-03 08:46 UTC, ManyTheFish commented on src/segmenter/chinese.rs
> +/// using HMM feature (Deactivated).
```suggestion
/// without using HMM feature.
```

2022-10-03 09:00 UTC, aniketh-varma commented on src/segmenter/chinese.rs
> +/// using HMM feature (Deactivated).
Sure, I will do the changes right away.

2022-10-03 14:03 UTC, ManyTheFish approved these changes
Great! Thank you for your contribution!

bors merge

2022-10-04 13:17 UTC, ManyTheFish commented
Hello @aniketh-varma,

The tests are failing, I suggest running `cargo test chinese` locally and modify the tests to make them work,

Thanks!

2022-10-05 12:01 UTC, ManyTheFish commented
Re @aniketh-varma,
Your work is conflicting with a [PR that has been recently merged](https://github.com/meilisearch/charabia/pull/143). You will have to make a small rebase before being able to merge your PR.

2022-10-12 15:27 UTC, closed without merging

2022-10-12 19:38 UTC, aniketh-varma commented
> Hello @aniketh-varma, the tests are failing and your branch is not up to date with the main branch, If you want to ensure the tests pass, you have to run `cargo test` locally.
> 
> here is the checklist to make the PR reviewable:
> 
> * [ ]  the command `cargo test` is successful
> * [ ]  the branch is up to date with `main`
> 
> I close this PR for now, don't hesitate to reopen it when you are ready! thanks!

Sure @ManyTheFish, I will make the changes in the tests and update the branch as well