Add korean support
meilisearch/charabia pull request #154
Opened 2022-10-13 10:42 UTC by qbx2

# Pull Request

## Related issue
Fixes #153 

## What does this PR do?
- Add korean support

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2022-10-13 13:15 UTC, ManyTheFish requested changes
Hello @qbx2,
I requested some small changes to reduce the Library size when only Japanese is used or when only Korean is used.
I let you make the changes before re-reviewing your PR.
By the way, your PR is still in draft, don't you want to convert it?

2022-10-13 13:15 UTC, ManyTheFish commented on Cargo.toml
> +korean = ["dep:lindera"]
```suggestion
korean = ["dep:lindera", "lindera/ko-dic"]
```

2022-10-13 13:15 UTC, ManyTheFish commented on Cargo.toml
> +lindera = { version = "=0.17.0", features = ["ipadic", "ko-dic"], optional = true }
```suggestion
lindera = { version = "=0.17.0", default-features = false, optional = true }
```

2022-10-13 13:15 UTC, ManyTheFish commented on Cargo.toml
>  japanese = ["dep:lindera"]
```suggestion
japanese = ["dep:lindera", "lindera/ipadic"]
```

2022-10-13 16:22 UTC, qbx2 commented
Actually, I’ve made this PR draft to add bench data.

2022-10-13 17:37 UTC, ManyTheFish commented
@qbx2 yes you're right! We should add benchmark cases for Korean!
I let you do it, it's quite simple! Then we will be able to merge your PR.

2022-10-17 14:03 UTC, ManyTheFish approved these changes
Hey @qbx2,
this PR looks good to me, I let bors run the test and, if everything goes well, your PR will be merged automatically.

Thank you a lot for your spontaneous contribution! 😄 

bors merge

2022-10-17 14:12 UTC, merged