Improve Arabic language segmentation
meilisearch/charabia pull request #205
Opened 2023-04-08 22:25 UTC by DrAliRagab

Arabic text is segmented by word boundaries and by punctuation. We need a workaround to segment the Arabic text that starts with `ال` (the) because it is not segmented by word boundaries. One possible solution is to segment any word that starts with `ال` into two words. The `ال` and the rest of the word. with this solution, we will have `الشجرة` (the tree) segmented into `ال` (the) and `شجرة` (tree). and if we search for `شجرة` (tree) or `الشجرة` (thetree) we will find results. Some Arabic text starts with `ال` and not meant to be (the) like `البانيا` (Albania). In this case, we will have `ال` and `بانيا` segmented. and if we search for `البانيا` we will find results.

# Pull Request

## Related issue
Fixes #<issue_number>

## What does this PR do?
- ...

## PR checklist
Please check if your PR fulfills the following requirements:
- [ ] Does this PR fix an existing issue, or have you listed the changes applied in the PR description (and why they are needed)?
- [ ] Have you read the contributing guidelines?
- [ ] Have you made sure that the title is accurate and descriptive of the changes?

Thank you so much for contributing to Meilisearch!

2023-04-08 22:40 UTC, DrAliRagab commented
> Regarding segmenter, in Arabic language the starting `ال` is almost in 95% of words (I assume) is equal to `the`. As you can see here when I am searching for `الدوري` which means `the league` I got results. However when I search for `دوري` which means `league` I got no results. ![Screenshot 2023-04-06 194209](https://user-images.githubusercontent.com/37520558/230456028-9207e888-59ea-4d05-bca3-3f20508e2ea1.png) ![Screenshot 2023-04-06 194239](https://user-images.githubusercontent.com/37520558/230456031-a6c43b84-138e-416b-afaa-4070635878d7.png)
> 
> While in some other words like `البانيا` which means `Albania`, the starting `ال` is not equal to `the` and it's part of the word. but it will not make any significant difference in the search results. If I search for `بانيا` which equals to `bania` and get results it's not a big deal.
> 
> But if I search for `دوري` which equals to `league` and get no results, while there are many results for `الدوري` which equals to `the league`, it's a big deal.
> 
> So I think any word starts with `ال` should be segmented to two words, the one with `ال` and the one without `ال` and the search should be done on both of them.

Regarding the currently used segmenter for Arabic language, Any Arabic word that starts with `ال` are not segmented correctly. Because it's segmented based on space and punctuations.

To fix this; we can segment any word starts with `ال` into `ال` and the rest of the word. so when any user search for the word with `ال` or without `ال` related results will be shown.

While in some other words like `البانيا` which means `Albania`, the starting `ال` is not equal to `the` and it's part of the word. but it will not make any significant difference in the search results.
If I search for `البانيا` (Albania) or `بانيا` (bania), results will be shown.

After building Meilisearch with this segmenter and after rebuilding the indexes the issue was resolved.
As in this screenshot, when I searched for `دوري` (league) I got the results which fixes the previous issue.

![Screenshot 2023-04-09 003319](https://user-images.githubusercontent.com/37520558/230745457-dd55d576-1206-4478-a68a-970969df8201.png)

2023-04-11 10:10 UTC, ManyTheFish requested changes

2023-04-11 10:10 UTC, ManyTheFish commented on charabia/src/segmenter/arabic.rs
> +            .flat_map(|lemma| lemma.split_inclusive(|c: char| c.is_ascii_punctuation()))
```suggestion
```
Is it necessary, the function `split_word_bounds` should have already done the job, no? 🤔

2023-04-11 10:15 UTC, ManyTheFish commented
Hello @DrAliRagab, could you add some benchmarks for the Arabic Language?

You have to add 2 texts of different sizes, the script will do the rest!

https://github.com/meilisearch/charabia/blob/7349df3fd461ca95d7b71835d5816634e1d63274/charabia/benches/bench.rs#L7-L26

2023-04-11 15:05 UTC, ManyTheFish approved these changes
Nice work! Thank you for your contribution.

bors merge

2023-04-11 15:11 UTC, merged