Guide feature proposals to the product discussions space
meilisearch/charabia pull request #96
Opened 2022-05-05 11:27 UTC by gmourier

☝️

2022-05-05 11:31 UTC, curquiza commented
Hum, I was thinking: is it something you want to tell only to the contributors, or in priority to the users (so in the README)?

2022-05-05 11:38 UTC, gmourier commented
I'm thinking about the potential people who come to this repo. 

We wanted to avoid them creating an issue here asking for a feature and guide them as best as possible in the product discussions space.

We could also add this message when creating an issue, as we did on the meilisearch repo. WDYT?


![Capture d’écran 2022-05-05 à 13 36 05](https://user-images.githubusercontent.com/3692335/166915576-1d472236-e33b-4fdd-8a03-2024171328d0.png)

2022-05-05 11:59 UTC, curquiza commented
yes issue template is one of the solutions!

2022-05-05 12:01 UTC, ManyTheFish commented
let's do both, thanks @gmourier

2022-05-05 14:48 UTC, curquiza submitted a review, later dismissed
Thanks guigui!!

2022-05-16 12:47 UTC, ManyTheFish requested changes

2022-05-16 12:47 UTC, ManyTheFish commented on .github/ISSUE_TEMPLATE/config.yml
> +    url: https://github.com/meilisearch/product/discussions/categories/feedback-feature-proposal
We should redirect to the specialized label, no?
```suggestion
    url: https://github.com/meilisearch/product/discussions?discussions_q=label%3Aproduct%3Acore%3Atokenizer
```

2022-05-16 12:47 UTC, ManyTheFish commented on .github/ISSUE_TEMPLATE/config.yml
> +    about: The feature requests and feedback regarding the already existing features are not managed in this repository. Please open a discussion in our dedicated product repository.
```suggestion
    about: The feature requests and feedback like language support are not managed in this repository. Please open a discussion in our dedicated product repository.
```

2022-05-16 16:00 UTC, ManyTheFish approved these changes
Thank you @gmourier!
bors merge

2022-05-16 16:04 UTC, merged